FROM jenkins/jenkins:lts-jdk17

USER root

# Install Python and required packages
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv python3-nltk ca-certificates && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Create symbolic links for python commands
RUN ln -sf /usr/bin/python3 /usr/bin/python && \
    ln -sf /usr/bin/pip3 /usr/bin/pip

# Set up a Python virtual environment
ENV VIRTUAL_ENV=/opt/venv
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Install Python packages in the virtual environment
RUN . $VIRTUAL_ENV/bin/activate && \
    pip install nltk && \
    python -c "import nltk; nltk.download('stopwords')"

# Install Jenkins plugins
COPY plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

USER jenkins

# Skip setup wizard
ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false 